---
- name: Ensure {{ container_engine }} exists
  package_facts:
    manager: auto
  failed_when: "'{{ container_engine }}' not in ansible_facts['ansible_facts']['packages']"

- name: Deploy docker images
  shell: GRAFANA_PASSWD={{grafana_password}} PROM_DIR={{prom_path}} {{ container_engine }} up -d