---
- name: set local grafana route
  set_fact:
    grafana_route: "http://localhost:{{ grafana_port}}"

- name: Ensure {{ container_engine }} is installed
  ansible.builtin.package:
    name: "{{ container_engine }}"
    state: present
 
- name: Get userid
  shell: echo $UID
  register: uid

- name: Deploy docker images
  shell: CUID={{uid.stdout}} GRAFANA_PASSWD={{grafana_password}} PROM_DIR={{prom_path}} PROMETHEUS_IMAGE_TAG={{prometheus_image_tag}} GRAFANA_IMAGE_TAG={{grafana_image_tag}} {{ container_engine }} up -d

- name: Get FQDN of the host
  ansible.builtin.command: hostname
  register: hostname

- name: Set local_grafana_fqdn
  set_fact:
    local_grafana_fqdn: "http://{{ hostname.stdout }}:{{ grafana_port }}"

- name: Fetch the TSDB time ranges
  shell: podman exec -it odf-grafana_local-prometheus_1 promtool tsdb list -r /prometheus
  register: tsdb_info
