---
- name: Deploy Grafana and Prometheus Locally
  hosts: localhost
  gather_facts: false
  vars: 
    deploy_local: yes
  roles:
    - common
    - prepare
    - local_deploy
    - grafana
    - dashboard
  tasks:
    - name: Show deployment summary
      pause:
        seconds: 0
        prompt: |
          {{ lookup('ansible.builtin.template', 'roles/grafana/templates/summary.j2') }}
