services:
  prom:
    image: prom/prometheus
    user: "${UID}:${UID}"
    volumes:
      - /tmp/prometheus:/prometheus:Z
    networks:
      - internal
    ports:
      - 8080:80

  grafana:
    image: grafana/grafana-oss
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWD}
    ports:
      - 3001:3000
    networks:
      - internal

networks:
  internal: {}