services:
  local-prometheus:
    image: docker.io/prom/prometheus:v${PROMETHEUS_IMAGE_TAG}
    container_name: local_prometheus
    user: ${CUID}:${CUID}
    restart: always
    volumes:
      - ${PROM_DIR}:/prometheus:Z
    networks:
      - internal
    ports:
      - 9100:9090

  grafana:
    image: docker.io/grafana/grafana:${GRAFANA_IMAGE_TAG}
    container_name: local_grafana
    depends_on:
      - local-prometheus
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWD}
    ports:
      - 3001:3000
    networks:
      - internal

networks:
  internal: {}
